### ISSUE TITLE
Check if database record is stored after get()

### ISSUE THREAD

**Issue by jrondorf** [filebase/Filebase#21]
Hi,

I am searching for a method to check if the database record is a new one, or if it was already stored in the file system.

```
// in this example, you would search an exact user name
// It would technically be stored as user_name.json in the directories
$item = $database->get(kingslayer);
```

This is giving me a document with the `id` kingslayer, regardless if it was already existing in the file system or not. I need some kind of method to check if the document is a newly created one, or if it is read from the filesystem (so already existed before).

Maybe I am not finding the correct method here...

**Comment by timothymarois** [comment]
Hey. 

Yeah, I know. I was thinking that before as well. Let me see if I can get an update for you on that. New version (v2) of the Filebase is almost ready. **Understanding if a record exist is important.**

What if we do something like, would return `true` or `false`

```php
$record = $database->has('kingslayer');
```

the `get` method allows you to create records easily, that's why it was designed to always be a blank record if it doesnt exist.

**Comment by timothymarois** [comment]
@jrondorf I've added a new release v1.0.19 with `$db->has()` method. Let me know if that solves it! Thanks for the feedback, keep them coming :)

**Comment by jrondorf** [comment]
Thanks a lot, will check.

https://github.com/filebase/Filebase/blob/1.0/src/Database.php#L13

;)

**Comment by timothymarois** [comment]
@jrondorf Good find! I honestly don't know if that should be hardcoded in there anyways. Not sure if anyone actually uses it.

**Comment by jrondorf** [comment]
Yes - IMHO it doesn't need to be hard coded. Something for v2 ;)
