### ISSUE TITLE
Validation on save(array) fails

### ISSUE THREAD

**Issue by jrondorf** [filebase/Filebase#22]
Just FYI:

Following validation on the save method when passing an array on a **new** Document fails.

Setting first the values with `set (array)` and saving afterwards works fine.

Makes sense when looking at:

https://github.com/filebase/Filebase/blob/1.0/src/Document.php#L64

If v2 of Filebase doesn't contain the `save(array)` method any more, all fine.

```
    public function testValidatingStringRequiredGood() {
        $db = new \Filebase\Database([
            'dir' => 'data',
            'validate' => [
                'name'   => [
                    'valid.type' => 'string',
                    'valid.required' => true
                ]
            ]
        ]);

        $db->flush(true);

        // TEST OK
        $db->get('test')->set(['name'=>'value'])->save();
        $this->assertEquals(true, true);
        $db->flush(true);

        // TEST FAILS
        $db->get('test')->save(['name'=>'value']);
        $this->assertEquals(true, true);
        $db->flush(true);
    }
```

**Comment by timothymarois** [comment]
@jrondorf Yeah the validation was an addon I built a while ago, I honestly haven't revisited that since I was thinking more of recreating a "scheme" system. If you have any pull request to improve functionality I'm totally open. As for v2. It is a bit more simplistic/modern approach to objects, using a `Collection` system instead, it won't have the `save(array)` functionality.

**Comment by jrondorf** [comment]
Yes, this was just a FYI, if v2 doesn't have that functionality, all fine.
