### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by shamuel22** [filebase/Filebase#29]
Hi, There is a benchmark to process a large amount of data? for example 1M of records

**Comment by timothymarois** [comment]
Hello @shamuel22 

We currently don't have a benchmark, but I would love to see one. This also depends on your I/O and read/write ability within the server drive, HDD, SSD etc. 

As for the 1 million records, you would need some better cache handling so you don't lock up the file system by trying to open up that many files at once within queries. I would also say if you want records that large, and you want to query them, then use MySQL or a SQL server since that is designed best for querying large data-sets. As for "storing" 1M records and accessing each at a single time, that is easy. The ability to query, that's where you might want to use a system designed specifically for that functionality on a large scale. 

Using a Flat File system with say a few hundred or even a few thousand, can easily handle that just fine. Getting up into that million is where you need to decide what's best for your application.

**Comment by shamuel22** [comment]
@timothymarois  I await more updates of this package. Meanwhile I will play a little with the code :)
