### ISSUE TITLE
Bad Pattern: Document->field('data')

### ISSUE THREAD

**Issue by landall** [filebase/Filebase#38]
it is not a good design to use special field name 'data' but other field name without a prefix 'data.'

It should be
   SomeDocument->field('data')
   SomeDocument->field('data.user.id')
or
   SomeDocument->field('')
   SomeDocument->field('user.id')

**Comment by timothymarois** [comment]
This is true. It was really due to morphing the data through either arrays or objects, and I needed to include a placeholder. Not to mention I wrapped it up in data so that anything above that could be like global variables such as `created_at`, `updated_at`.  I am open to pull requests for needed changes. I would love to revamp this, such as Filebase v2.

**Comment by landall** [comment]
I find it affacts to __set & __get of a document.

SomeDocument->fieldA should be changed to SomeDocument->data->fieldA.

I guess this is why you need a special field named data.

**Comment by timothymarois** [comment]
@landall Yeah exactly. I think v1.0 will have to stick with that format, but I am open to revisions for a future version that simplifies this. v2.0 I want to use a collection system instead.
